export const INCREMENT = 'increment'
export const DECREMENT = 'decrement'
export const INCREMENTCOUNT = 'incrementCount'
export const SAVESTUDENT = 'saveStudent'
export const CHANGEINFO = 'changeInfo'
export const UPDATENAME = 'updateName'
